name: contactbook
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  uuid: ^3.0.7
  fast_contacts: ^1.0.0
  permission_handler: ^10.2.0
  cross_file_image: ^1.0.0
  favorite_button: ^0.0.4
  flutter_profile_picture: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/contact_book_icon.png"  

flutter:
  assets:
    - assets/

  uses-material-design: true

